name = "PortfolioOptimisersGUI"
uuid = "54ab21c9-f8d7-5af7-a33b-8d663c3a89b5"
version = "0.1.0"
authors = ["Daniel Celis Garza <daniel.celis.garza@gmail.com>"]

[workspace]
projects = ["test", "docs"]

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
PortfolioOptimisers = "e0036ec9-05e5-505d-a6a9-07af41c94861"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
ArgCheck = "2.5.0"
ConcreteStructs = "0.2.6"
GraphRecipes = "0.5.16"
PortfolioOptimisers = "0.25.0"
StatsPlots = "0.15.8"
julia = "1.12"
